### PR TITLE
generalizing tissue name to uberon mapping

### PR DESCRIPTION
**Pull request by DSuveges**
- This work is done as part of the project score v2 data update [#3027](https://github.com/opentargets/issues/issues/3027).
- The depmap to uberon mapping is generalized to sanger model passport tissue labels as well.
- The updated mapping file has a slightly different set of tissue labels that reflects the complete set of tissues from the [Cell Model Passports](https://cellmodelpassports.sanger.ac.uk/)
- To make the schema more general there are a few assumptions: tissue names are all lower case characters. Tissue names are in the `tissueFromSource` column. Use this column to join with data to be mapped. (Ideally synonyms should be captured as lists, but this is not critical)
- This PR depends on update on the [depmap parser](https://github.com/opentargets/evidence_datasource_parsers/pull/159)

### CODE REVIEW

**Review by ireneisdoomed — APPROVED** [review]
Thank you Daniel, additions make sense. Having the strings in lower case makes sense as well.
It would be nice to include some brief explanation about the provenance of this curation in `docs/mappings.md`. These have been mapped by you, it is not coming from Cell Models Passports right?

**Comment by DSuveges** [comment]
> . These have been mapped by you, it is not coming from Cell Models Passports right?

Yes, that's right. I'm adding comments on the readme.

**Review by ireneisdoomed — CHANGES_REQUESTED** [review]
Ty for the extra docs! Could you please add it to the existing docs file? All the docs for this repo are within `docs/` https://github.com/opentargets/curation/blob/master/docs/mappings.md

**Review by ireneisdoomed — APPROVED** [review]
Thanks!

**Pull request merged**
