### PR TITLE
Convert mappings back into URIs, normalise and update the script

### PR DESCRIPTION
**Pull request by tskir**
This is a follow up for https://github.com/opentargets/curation/pull/8. Closes https://github.com/opentargets/issues/issues/1400.

* Fixed the bug in the normalisation script to enable stable sorting by disease name and mapping URI
* Change the compact identifiers back into full URIs for compatibility with ZOOMA 8-column format
* Normalised the list of mappings using the updated version of the script

Normalisation report:
```
Total: 25568 [efo/0_all.tsv]
  Mapping target cannot be parsed: 0 [efo/1a_cannot_parse_mapping.tsv]
  Mapping target can be parsed: 25568
    Duplicates: 209 (removed)
    Unique: 25359 [efo/2_unique.tsv]
      Not in EFO: 639 [efo/3a_not_in_efo.tsv]
      In EFO but obsolete: 969 [efo/3b_obsolete.tsv]
      In EFO and live (current): 23751 [efo/3c_live.tsv]
Total mappings after normalisation: 25359 [efo/manual_string_NORM.tsv]
```

**Note** that, in its current version, the normalisation script only keeps one record for each unique string/URI pair. For example, if we have "Whole body water mass" mapped to http://www.ebi.ac.uk/efo/EFO_0009805, but coming from multiple sources (Genebass and AstraZeneca PheWAS Portal in this example), only one curated mapping will be kept (the most recent one according to the timestamp in the last column). Please let me know if you think that this behaviour should be changed.

You can see the list of mappings which were removed in this commit: https://github.com/opentargets/curation/pull/9/commits/ffe613150740ca0e1a0448affb1dc312624bc1d2

### CODE REVIEW

**Review by ireneisdoomed — COMMENTED** [review]
Love the branch name haha
Changes look fine to me. The only problem is that the master branch has been updated afterwards to update some mappings ( see [commit](https://github.com/opentargets/curation/commit/d07ef4c040c25b5a7a2368ef8797d202609517f1))

Did you do the conversion to the full URI manually?

**Comment by tskir** [comment]
@ireneisdoomed I've now rebased it against the main branch and reintroduced the changes you made in https://github.com/opentargets/curation/commit/d07ef4c040c25b5a7a2368ef8797d202609517f1.

However, one thing strikes me as a bit odd. Out of seven "Z12" terms ("examination for neoplasm..."), the first two are mapped to http://www.ebi.ac.uk/efo/EFO_0021523  "examination for neoplasm", while the rest are still mapped to a more general http://www.ebi.ac.uk/efo/EFO_0009517 "checkup".

I assumed this was not intentional, and made all those terms map to the more specific term "examination for neoplasm" in this latest commit: https://github.com/opentargets/curation/pull/9/commits/623cdfe53169275dc67324079600bb3cffbf14ad. But please let me know if this was in fact intentional, and then I can revert it.

**Comment by tskir** [comment]
The most recent normalisation script report on this branch:

```
Total: 25358 [efo/0_all.tsv]
  Mapping target cannot be parsed: 0 [efo/1a_cannot_parse_mapping.tsv]
  Mapping target can be parsed: 25358
    Duplicates: 0 (removed)
    Unique: 25358 [efo/2_unique.tsv]
      Not in EFO: 645 [efo/3a_not_in_efo.tsv]
      In EFO but obsolete: 969 [efo/3b_obsolete.tsv]
      In EFO and live (current): 23744 [efo/3c_live.tsv]
Total mappings after normalisation: 25358 [efo/manual_string_NORM.tsv]
```

**Comment by ireneisdoomed** [comment]
Thank you for the changes!!
I think there is something I am missing in the newer table. The number of mappings has decreased ~200 records. I did the anti join of the table in master and the new one and there are 2 traits that we are losing:
```
In [51]: old.merge(new, on='PROPERTY_VALUE', how='left', indicator=True).query('_merge == "left_only"')
Out[51]:
            STUDY_x  BIOENTITY_x PROPERTY_TYPE_x       PROPERTY_VALUE SEMANTIC_TAG_x  ANNOTATOR_x    ANNOTATION_DATE_x STUDY_y  BIOENTITY_y PROPERTY_TYPE_y SEMANTIC_TAG_y ANNOTATOR_y ANNOTATION_DATE_y     _merge
491   Target safety          NaN         disease  atrial fibrillation    EFO_0000275  Irene Lopez  2021-11-02 12:00:00     NaN          NaN             NaN            NaN         NaN               NaN  left_only
2906  Target safety          NaN         disease        heart failure    EFO_0003144  Irene Lopez  2021-11-02 12:00:00     NaN          NaN             NaN            NaN         NaN               NaN  left_only
```

Re `examination for neoplasm`, well spotted. This was not intentional.

**Comment by tskir** [comment]
@ireneisdoomed I've investigated your latest comment. The apparent loss of "atrial fibrillation" and "heart failure" etc. is also due to an update in deduplication policies. Starting from this PR, if the records only differ in case (such as `atrial fibrillation` vs. `Atrial fibrillation`), but point to the same ontology term, only one is kept, (because they convey essentially the same information).

It is assumed that every piece of code which uses the `manual_string.tsv` file will do normalisation by case; this is already always happening in OnToma and ZOOMA. However, to make sure that this is stated explicitly, I've updated the documentation to reflect the current behaviour: https://github.com/opentargets/curation/commit/3a464dde912d0aca1f573a03644924767ff61d3f

**Pull request merged**
