### PR TITLE
feat: release 2024-08 curation manifest

### PR DESCRIPTION
**Pull request by project-defiant**
Curation of new batch of GWAS Catalog sumstats - by @addramir.

The curation file had a few duplicates - removed them  - see https://github.com/opentargets/issues/issues/3412#issuecomment-2283967916

### CODE REVIEW

**Comment by project-defiant** [comment]
@ireneisdoomed please could you review?

**Comment by project-defiant** [comment]
@ireneisdoomed, thank you for checking it, these may have been added somehow during the curation I am double checking it.

**Comment by project-defiant** [comment]
The issue was how I removed the duplicates, I have retained two of them where all columns were not identical. I have updated this file and the `gs://genetics_etl_python_playground/input/v2d/GWAS_Catalog_study_curation_dedup_2024-08-12.tsv`. Thank you for double checking it !

**Review by ireneisdoomed — APPROVED** [review]
Thanks!

**Pull request merged**
